# Etapa de build
FROM node:18-alpine AS builder
WORKDIR /app
COPY vite-project/package*.json ./
RUN npm install
COPY vite-project ./
RUN npm run build

# Etapa de produção
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]