apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-high-alert
  labels:
    release: prometheus
spec:
  groups:
    - name: node
      rules:
        - alert: HighCpuUsage
          expr: 100 * (1 - avg(irate(node_cpu_seconds_total{mode="idle"}[2m])) by (instance)) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Node {{ $labels.instance }} CPU usage is above 80% for 2 minutes."