version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eventos_postgres
    restart: always
    environment:
      POSTGRES_USER: eventos_user
      POSTGRES_PASSWORD: eventos_pass
      POSTGRES_DB: eventos_db
    ports:
      - "5432:5432"
    command: ["postgres", "-p", "5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      # Para inicializar com um schema customizado, descomente a linha abaixo:
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  adminer:
    image: adminer
    container_name: eventos_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    # Para buildar localmente:
    # build: .
    # Para usar uma imagem específica para rollback, comente o build e descomente a linha abaixo:
    image: backend-backend:v1
    command: gunicorn -b 0.0.0.0:8000 wsgi:app
    volumes:
      - .:/app
      - ./backups:/backups
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: