apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-crash-alert
  labels:
    release: prometheus
spec:
  groups:
    - name: pods
      rules:
        - alert: PodCrashLooping
          expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod crash looping detected"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping for more than 5 minutes."