version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eventos_postgres
    restart: always
    environment:
      POSTGRES_USER: eventos_user
      POSTGRES_PASSWORD: eventos_pass
      POSTGRES_DB: eventos_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  adminer:
    image: adminer
    container_name: eventos_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build: .
    command: gunicorn -b 0.0.0.0:8000 wsgi:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: