services:
  db:
    image: postgres:15
    container_name: eventos_postgres
    restart: always
    environment:
      POSTGRES_USER: eventos_user
      POSTGRES_PASSWORD: eventos_pass
      POSTGRES_DB: eventos_db
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  adminer:
    image: adminer
    container_name: eventos_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build: .
    volumes:
      - .:/app
      - ./backups:/backups
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: