apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: henrique99sl/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://eventos_user:eventos_pass@eventos-postgres:5432/eventos_db
            - name: FLASK_ENV
              value: development
            - name: SECRET_KEY
              value: sua_chave_muito_secreta
            - name: JWT_SECRET_KEY
              value: sua_jwt_ultra_secreta
            - name: CORS_ORIGINS
              value: http://localhost:3000
            - name: SENTRY_DSN
              value: ""