apiVersion: v1
kind: Service
metadata:
  name: eventos-postgres         # <-- Corrigido!
spec:
  selector:
    app: eventos-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432