apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_USER: "eventos_user"
  DB_PASSWORD: "eventos_pass"
  SECRET_KEY: "sua_chave_muito_secreta"
  JWT_SECRET_KEY: "sua_jwt_ultra_secreta"