"""add unique constraint to email

Revision ID: 87a975419bb5
Revises: 8cd7ce8eac19
Create Date: 2025-08-10 15:30:53.659561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87a975419bb5"
down_revision = "8cd7ce8eac19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=80),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=80),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
