"""Descrição

Revision ID: 8ee0638a1160
Revises: 0bc15a8e839b
Create Date: 2025-08-12 19:03:00.028129

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8ee0638a1160"
down_revision = "0bc15a8e839b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
