"""Corrige ForeignKey Feedback para users.id

Revision ID: aebe48e470ac
Revises: 5deb6daa635c
Create Date: 2025-08-23 15:13:59.890391

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aebe48e470ac"
down_revision = "5deb6daa635c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.String(length=32), nullable=True),
        sa.Column("topics", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
