name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint, Validate Swagger and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      FLASK_ENV: test
      TESTING: "True"
      REDIS_URL: redis://localhost:6379/0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics

      - name: Validate Swagger/OpenAPI
        run: |
          pip install openapi-spec-validator
          if [ -f swagger.yaml ]; then openapi-spec-validator swagger.yaml; fi

      - name: Run tests and generate coverage
        run: |
          pip install pytest-cov
          pytest --cov=. --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: backend/coverage.xml

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-flask-app .